config/routes.rb
# Rails.application.routes.draw do
#   # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

#   # Defines the root path route ("/")
#   # root "articles#index"
#   get 'restaurants', to: 'restaurants#index'

#   get 'restaurants/new', to: 'restaurants#new'
#   post 'restaurants', to: 'restaurants#create'

#   get 'restaurants/:id', to: 'restaurants#show', as: :restaurant

#   get '/restaurants/:id/reviews/new',
# end

# Rails.application.routes.draw do
#   resources :restaurants do
#     resources :reviews, only: [:new, :create]
#   end
#   resources :reviews, only: [:show, :edit, :update, :destroy]
# end

Rails.application.routes.draw do
  resources :restaurants, { shallow: true } do
    resources :reviews, except: [:new]
  end
end

# Rails.application.routes.draw do
#   resources :restaurants do
#     resources :reviews, only: [:index, :new, :create]
#   end
#   resources :reviews, only: [:show, :edit, :update, :destroy]
# end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :reviews, dependent: :destroy

  validates :name, presence: true
  validates :address, presence: true
  validates :category, presence: true, inclusion: { in: %w[chinese italian japanese french belgian] }
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant

  validates :content, presence: true
  validates :rating, presence: true, numericality: { in: 0..5, only_integer: true }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  def index
    @restaurants = Restaurant.all
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)

    if @restaurant.save
      redirect_to @restaurant, notice: 'Restaurant was successfully created.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @restaurant = Restaurant.find(params[:id])
    @review = Review.new
  end

  def review
    @review = @restaurant.review
  end

  private

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :phone_number, :category)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_restaurant, only: %i[new create]

  def create
    @review = Review.new(review_params)
    @review.restaurant = @restaurant
    if @review.save
      redirect_to restaurant_path(@restaurant)
    else
      @restaurant = Restaurant.find(params[:restaurant_id])
      render 'restaurants/show', status: :unprocessable_entity
    end
  end

  private

  def set_restaurant
    @restaurant = Restaurant.find(params[:restaurant_id])
  end

  def review_params
    params.require(:review).permit(:content, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light px-5 mb-3">
  <div class="container">
    <a class="navbar-brand" href="#">Yelp</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
      <div class="navbar-nav">
        <a class="nav-item nav-link active" href="/restaurants/">Home</a>
        <a class="nav-item nav-link" href="/restaurants/new">Add a restaurant</a>
      </div>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
  </head>

  <body>
  <%= render "layouts/navbar" %>
    <%= yield %>
  </body>
</html>

app/views/restaurants/_form.html.erb
<%= simple_form_for(@restaurant) do |f| %>
  <%= f.input :name %>
  <%= f.input :address %>
  <%= f.input :phone_number %>
  <%= f.input :category %>
  <%= f.submit %>
<% end %>

app/views/restaurants/index.html.erb
<div class="container">
<ul class="list-group">
    <% @restaurants.each do |restaurant| %>
    <li class="list-group-item d-flex justify-content-between align-items-start">
      <div class="ms-2 me-auto">
        <%= link_to restaurant_path(restaurant), style: 'text-decoration: none' do %><%= restaurant.name %></div>
        <% end %>
      <span class="badge bg-primary rounded-pill"><%= restaurant.category %></span>
    </li>
    <% end %>
  </ul>
</div>

app/views/restaurants/new.html.erb
<div class="container">
  <%= render "form", task: @restaurant %>
</div>

app/views/restaurants/show.html.erb
<div class="container">
  <h2><%= @restaurant.name %></h2>
  <p><%= @restaurant.address %></p>
  <p><%= @restaurant.phone_number %></p>
  <p><%= @restaurant.category %></p>
  <p><strong>Reviews</strong></p>
  <ul class="list-group">
  <%# <p><%= link_to "New review", new_restaurant_review_path(@restaurant), class: "btn btn-primary" %>
  <%# <p><%= render "form", task: @review %>
  <p><%= render :partial => "reviews/form" %></p>
    <% @restaurant.reviews.each do |review| %>
      <li class="list-group-item"><%= review.content %> - <%= review.rating %> / 5</li>
    <% end %>
  </ul>
</div>

app/views/reviews/_form.html.erb
<%= simple_form_for [@restaurant, @review] do |f| %>
  <%= f.input :content %>
  <%= f.input :rating %>
  <%= f.submit "Submit review", class: "btn btn-primary" %>
<% end %>